# Funding options for the project
# Uncomment and add your details if you want to accept donations

# github: [your-github-username]
# ko_fi: your-kofi-username
# patreon: your-patreon-username
# custom: ["https://your-donation-link.com"]
