# Auto-label PRs based on changed files

# Bot core
'bot-core':
  - 'bot.py'
  - 'market_simulator.py'
  - 'market_updates.py'

# Commands
'commands':
  - 'commands_*.py'

# Configuration
'configuration':
  - 'config.py'
  - '.env.example'

# Database
'database':
  - 'database.py'
  - 'data/**/*'

# Documentation
'documentation':
  - 'docs/**/*'
  - '*.md'
  - 'README.md'

# CI/CD
'ci-cd':
  - '.github/workflows/**/*'
  - '.github/dependabot.yml'

# Dependencies
'dependencies':
  - 'requirements.txt'

# Security
'security':
  - 'SECURITY.md'
  - '.gitignore'

# UI/UX
'ui-ux':
  - 'graphing.py'

# Utilities
'utilities':
  - 'utils.py'
  - 'team_detection.py'

# Market
'market':
  - 'market.py'
  - 'data/stocks/**/*'
